### PR TITLE
increase contrast and readability of banner

### PR DESCRIPTION
**Pull request by zeke**
## Before

screen shot 2017-02-01 at 7 31 12 pm

## After

screen shot 2017-02-01 at 7 30 45 pm

### CODE REVIEW

**Comment by zeke** [comment]
I found this browser extension on https://github.com/bkeepers/stop-trump. Thanks, @bkeepers!

**Comment by timothyis** [comment]
Perhaps add back the underline on the links so that it's obvious they're links? 😁

**Comment by zeke** [comment]
Oops. The underlines are missing in my screenshot, but I think they're actually still visible. This was me hacking the styles in devtools and copying them over. Haven't actually tried loading the extension from disk.

**Comment by egonSchiele** [comment]
Thanks!

**Pull request merged**
